[metadata]
name = nova-incus
version = 2026.1.0
summary = Native Incus system-container driver for OpenStack Nova
description_file =
    README.md
author = OpenStack
author_email = openstack-discuss@lists.openstack.org
home_page = https://www.openstack.org/
classifier =
    Environment :: OpenStack
    Intended Audience :: Information Technology
    Intended Audience :: System Administrators
    License :: OSI Approved :: Apache Software License
    Operating System :: POSIX :: Linux
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: 3.12

[files]
packages =
    nova_incus_tempest_plugin

[entry_points]
console_scripts =
    nova-incus-compute = nova.virt.incus.cmd.compute:main
tempest.test_plugins =
    nova-incus-tempest-plugin = nova_incus_tempest_plugin.plugin:NovaIncusTempestPlugin

[build_sphinx]
source-dir = doc/source
build-dir = doc/build
all_files = 1
